config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => :registrations
  resources :comfort_types

  resources :cars
  root 'cars#index'
  get '/make_car_available', to: 'cars#car_available', via: [:post] 
  resources :rents, :only => [:create]    
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :comfort_type
  has_many :rents
  validates_presence_of :name, :description, :comfort_type_id
  validates :photo1, :photo2, :photo3, :attachment_presence => true
  has_attached_file :photo1, :styles => { :medium => "640x480>", :thumb => "160x120>" }
  validates_attachment_content_type :photo1, :content_type => /\Aimage\/.*\Z/            
  has_attached_file :photo2, :styles => { :medium => "640x480>", :thumb => "160x120>" }
  validates_attachment_content_type :photo2, :content_type => /\Aimage\/.*\Z/ 
  has_attached_file :photo3, :styles => { :medium => "640x480>", :thumb => "160x120>" }
  validates_attachment_content_type :photo3, :content_type => /\Aimage\/.*\Z/
end

app/models/comfort_type.rb
class ComfortType < ActiveRecord::Base
  has_many :cars
  validates_presence_of :name
  validates :price, :presence => true,
              :numericality => true,
              :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }  
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :car
  validates_presence_of :no_of_days, :car_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  include ApplicationHelper
  before_action :check_isadmin?, only: [:new, :edit, :update, :create, :destroy]
  expose(:cars)
  expose(:car, attributes: :car_params)
  expose(:comfort_types) 
  expose(:comfort_type) 
  def show
    @rent = Rent.new
  end      
  def create
    self.car = Car.new(car_params)
    if car.save
      redirect_to(car, notice: 'Car was successfully created.')
    else
      render :new
    end
  end

  def update
    if car.save
      redirect_to(car, notice: 'Car was successfully updated.')
    else
      render :edit
    end
  end 

  def destroy
    car.destroy
    redirect_to cars_url, notice: 'Car was successfully destroyed.'
  end
  def car_available
    car_id = params[:format].to_i    
    @car = Car.find(car_id)
    @car.update(available: true)
  end
  private
    def car_params
      params.require(:car).permit(:name, :description, :comfort_type_id, :available, :photo3, :photo2, :photo1)
    end
end

app/controllers/comfort_types_controller.rb
class ComfortTypesController < ApplicationController
  include ApplicationHelper
  before_action :check_isadmin?
  expose(:comfort_types) 
  expose(:comfort_type, attributes: :comfort_type_params)  
 
  def create
    self.comfort_type = ComfortType.new(comfort_type_params)
    if comfort_type.save
      redirect_to(comfort_type, notice: 'Comfort type was successfully created.')
    else
      render :new
    end
  end

  def update
    if comfort_type.update(comfort_type_params)
      redirect_to(comfort_type, notice: 'Comfort type was successfully updated.')
    else
      render :edit
    end
  end 

  def destroy
    comfort_type.destroy
    redirect_to comfort_types_url, notice: 'Comfort type was successfully destroyed.'
  end

  private
    def comfort_type_params
      params.require(:comfort_type).permit(:name, :price)
    end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  include ApplicationHelper
  before_action :check_isadmin?
  def create
    @rent = Rent.new(rent_params)
    @car = Car.find(rent_params[:car_id])
    @car.update(available: false)
    respond_to do |format|
      if @rent.save
        format.js { }
      else
        format.js { }
      end
    end
  end
  def rent_params
    params.require(:rent).permit(:no_of_days, :car_id)
  end      
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_isadmin?
    unless current_user.try(:admin?)
      redirect_to new_user_session_path
    end
  end  
  def is_active_page?(link_path)
    if current_page?(link_path)
      return "active" if request.query_parameters.empty?     
    else
      ""
    end    
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comfort_types_helper.rb
module ComfortTypesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/cars/_form.html.erb
<%= form_for car, :html => { :multipart => true }, :html => { :class => 'form-horizontal' } do |f| %>
  <% if car.errors.any? %>
    <div class="row">
    	<div class="row">
    	<div class="col-lg-2">
    	</div>
    	<div class="col-lg-8">
    		<div class="alert alert-dismissable alert-danger">
    		  <strong><%= pluralize(car.errors.count, "error") %> prohibited this photo_post from being saved:</strong>
	    	  <ul>
		      <% car.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
    		</div>
    	</div>  	      
    	<div class="col-lg-2">
    	</div>	      
    	</div>
    </div>
  <% end %>



  <div class="form-group">
    <%= f.label "Car name", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-4">
      <%= f.text_field :name, :class => 'form-control', :id => "Input", :placeholder => "Car name" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Description", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-4">
      <%= f.text_area :description, :class => 'form-control', :id => "Input", :placeholder => "Description of car" %>
    </div>
  </div> 
  
  <div class="form-group">
    <%= f.label "Comfort type", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-4">
 	<%= f.select :comfort_type_id, comfort_types.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Comfort type'}, :class => 'form-control'%>
    </div>
  </div>  
  
  <div class="form-group">
    <%= f.label "Photo1", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-4">
      <%= f.file_field :photo1, :class => 'form-control' %>
    </div>    
  </div>
  
  <div class="form-group">
    <%= f.label "Photo2", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-4">
      <%= f.file_field :photo2, :class => 'form-control' %>
    </div>    
  </div>  
  
  <div class="form-group">
    <%= f.label "Photo3", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-4">
      <%= f.file_field :photo3, :class => 'form-control' %>
    </div>    
  </div>    
    
        
  <div class="form-group">
  	<div class="col-lg-4 col-lg-offset-2">
        <div class="checkbox">
          <label>
            <%= f.check_box :available %> Available
          </label>
        </div> 
  	</div>
  </div>        
        
        
  <div class="form-group">
  	<div class="col-lg-4 col-lg-offset-2">
    <%= f.submit "Save", :class => 'btn btn-primary' %>
  	</div>
  </div>   
<% end %>

app/views/cars/edit.html.erb
<div class="row">
	<div class="col-lg-2">
	</div>
	<div class="col-lg-8">
		<h1>Editing car</h1>
	</div>	
	<div class="col-lg-2">
	</div>
</div>
<div class="row">
	<%= render 'form' %>
</div>

app/views/cars/index.html.erb
<h1>OUR CARS</h1>



    <% cars.each do |car| %>
		<div class="well bs-component">
			<div class="row">
				<a href="/cars/<%= car.id%>">
				<div class="col-lg-4">
				<%= image_tag car.photo1.url(:thumb), :class => 'img-circle'  %>
				<h3 class="text-danger">Comfort type: <%= car.comfort_type.try(:name)%></h3>	
				<h4 class="text-info">Price per day: <%= number_to_currency(car.comfort_type.try(:price), :unit => "zł")%></h4>
				</div>
				<div class="col-lg-4">
				<h3><%= car.name%></h3>
				<small><%= car.description%></small>
				</div>
				</a>
				<div class="col-lg-4">
				<% if  car.available == true %>
				<h3>Car is available</h3>
				<%= image_tag("yes.png", size: "150x150") %>
				<% elsif  car.available == false%>
				<% last_rent = Rent.where(car_id: car.id).last.created_at%>
				<% no_of_days = Rent.where(car_id: car.id).last.no_of_days%>
				<h4 class="text-danger">Car is not available until: <br /> <%=(last_rent + no_of_days.day).to_formatted_s(:short)%></h4>
				<%= image_tag("no.png", size: "150x150") %>		
				<% end %>
				<% if  car.available == false && current_user.try(:admin?) %>
					<%= link_to 'CHANGE TO AVAILABLE', make_car_available_path(car), :remote => true, class: "btn btn-danger btn-xs change-av" %>
				<% end %>
				</div>									
			</div>	
		</div>
    <% end %>

<br>
<% if  current_user.try(:admin?) %>
<%= link_to 'Add New Car', new_car_path, :class => 'btn btn-primary' %>
<% end %>
<script>
$( ".change-av" ).click(function() {
$( this ).parent().html('<h3>Car is avilable</h3><img src="/assets/yes.png" width="150" height="150"/>');
});
</script>

app/views/cars/new.html.erb
<div class="row">
	<div class="col-lg-2">
	</div>
	<div class="col-lg-8">
		<h1>New car</h1>
	</div>	
	<div class="col-lg-2">
	</div>
</div>
<div class="row">
	<%= render 'form' %>
</div>

app/views/cars/show.html.erb
<div class="row">
<div class="col-lg-8">
<div class="jumbotron">	
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="width: 640px;">
	<ol class="carousel-indicators">
	 <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
	 <li data-target="#carousel-example-generic" data-slide-to="1"></li>
	 <li data-target="#carousel-example-generic" data-slide-to="2"></li>
	</ol>
    <div class="carousel-inner" role="listbox">
     <div class="item active">
      <%= image_tag car.photo1.url(:medium) %>
     </div>
     <div class="item">
      <%= image_tag car.photo2.url(:medium) %>
     </div>
     <div class="item">
      <%= image_tag car.photo3.url(:medium) %>
     </div>    
    </div>
	  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left"></span>
	  </a>
	  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right"></span>
	  </a>
</div>
</div>
</div>
<div class="col-lg-4">
<div class="jumbotron">		
	<h3><%= car.name%></h3>
	<small><%= car.description%></small>
	<h3 class="text-danger">Comfort type: <%= car.comfort_type.try(:name)%></h3>	
	<h4 class="text-info">Price per day: <%= number_to_currency(car.comfort_type.try(:price), :unit => "zł")%></h4>	
	<% if  car.available == true %>
	<h3>Car is available</h3>
	<%= image_tag("yes.png", size: "150x150") %>
	<% elsif  car.available == false%>
	<% last_rent = Rent.where(car_id: car.id).last.created_at%>
	<% no_of_days = Rent.where(car_id: car.id).last.no_of_days%>
	<h3 class="text-danger">Car is not available until: <br /> <%=(last_rent + no_of_days.day).to_formatted_s(:short)%></h3>	
	<%= image_tag("no.png", size: "150x150") %>		
	<% end %>
</div>		
</div>	
</div>
<% if current_user.try(:admin?) %>
<% if  car.available == true %>
<div class="row">
<div class="col-lg-4">
</div>	
<div class="col-lg-4">
<div class="well bs-component">
<div id="rent" class="alert alert-dismissable alert-danger">
</div>	
<script>$('#rent').hide();</script>		
<%= form_for(@rent, remote: true, :html => { :class => 'form-horizontal' }) do |f| %> 
<legend>Rent</legend>

  <div class="form-group">
    <%= f.label "Select number of days", :class => 'col-lg-3 control-label' %>
    <div class="col-lg-6">
    <%= f.select :no_of_days, (1..15) %>
    </div>
  </div> 

  <%= f.hidden_field :car_id, :value => car.id %> 
  <div class="form-group">
  	<div class="col-lg-6 col-lg-offset-3">
    <%= f.submit "Rent car", :class => 'btn btn-primary' %>
  	</div>
  </div>    
<% end %>
</div>
</div>
<div class="col-lg-4">
</div>
</div>
<% end %>
<div class="row">
<div class="col-lg-4">
</div>	
<div class="col-lg-4">
<%= link_to 'Edit', edit_car_path(car), :class => 'btn btn-primary' %>
<%= link_to 'Back', cars_path, :class => 'btn btn-info' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              car_path(car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<div class="col-lg-4">
</div>
</div>
<% end %>

app/views/comfort_types/_form.html.erb
<%= form_for comfort_type, :html => { :multipart => true }, :html => { :class => 'form-horizontal' } do |f| %>
  <% if comfort_type.errors.any? %>
    <div class="row">
    	<div class="row">
    	<div class="col-lg-2">
    	</div>
    	<div class="col-lg-8">
    		<div class="alert alert-dismissable alert-danger">
    		  <strong><%= pluralize(comfort_type.errors.count, "error") %> prohibited this photo_post from being saved:</strong>
	    	  <ul>
		      <% comfort_type.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
    		</div>
    	</div>  	      
    	<div class="col-lg-2">
    	</div>	      
    	</div>
    </div>
  <% end %>



  <div class="form-group">
    <%= f.label "Comfort type name", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-4">
      <%= f.text_field :name, :class => 'form-control', :id => "Input", :placeholder => "Comfort type name" %>
    </div>
  </div> 
  
  <div class="form-group">
    <%= f.label "Price per day", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-4">
      <%= f.text_field :price, :class => 'form-control', :id => "Input", :placeholder => "Enter price in format 9.99" %>
    </div>
  </div>       
        
  <div class="form-group">
  	<div class="col-lg-4 col-lg-offset-2">
    <%= f.submit "Save", :class => 'btn btn-primary' %>
  	</div>
  </div>   
<% end %>

app/views/comfort_types/edit.html.erb
<div class="row">
	<div class="col-lg-2">
	</div>
	<div class="col-lg-8">
		<h1>Editing comfort_type</h1>
	</div>	
	<div class="col-lg-2">
	</div>
</div>
<div class="row">
	<%= render 'form' %>
</div>

app/views/comfort_types/index.html.erb
<div class="row">
<div class="col-lg-8">
<div class="page-header">
	  <h1 id="tables">All comfort types </h1>
</div>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price per day</th>
      <th>Actions</th>      
    </tr>
  </thead>
  <tbody>
  <% idx = 0 %>	
  <% comfort_types.each do |comfort_type| %>
	  <% idx = idx + 1 %>
	  <% if(idx % 6 == 0) %>  
	  <% idx = 1 %>
	  <% end %>
	  <% if(idx % 5 == 0) %>
	  	<tr  class="active">
	  <% elsif(idx % 4 == 0) %>
	  	<tr  class="warning">
	  <% elsif(idx % 3 == 0) %>
	  	<tr  class="danger">
	  <% elsif(idx % 2 == 0) %>
	  	<tr  class="success">
	  <% elsif (idx % 1 == 0)%>		
	  	<tr  class="info">
	  <% end %>
      <td><a href="/comfort_types/<%= comfort_type.id %>" class="tlink">
	  <div class="td-link">
      	<%= comfort_type.name %>
      </div></a></td>	
      
      <td><a href="/comfort_types/<%= comfort_type.id %>" class="tlink">
	  <div class="td-link">
	  	<%= number_to_currency(comfort_type.price, :unit => "zł")%>
	  </div></a></td>
	  
      <td><%= link_to 'Show', comfort_type, :class => 'btn btn-success btn-xs' %>
      <%= link_to 'Edit', edit_comfort_type_path(comfort_type), :class => 'btn btn-info btn-xs' %>
      <%= link_to 'Destroy', comfort_type, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger  btn-xs' %>
      </td>      
    </tr>
  <% end %>   	
  </tbody>
</table>
<center>
</center>
<%= link_to 'New comfort type', new_comfort_type_path, :class => 'btn btn-primary' %>
</div> 
<div class="col-lg-4">
</div> 	
</div>

app/views/comfort_types/new.html.erb
<div class="row">
	<div class="col-lg-2">
	</div>
	<div class="col-lg-8">
		<h1>New comfort type</h1>
	</div>	
	<div class="col-lg-2">
	</div>
</div>
<div class="row">
	<%= render 'form' %>
</div>

app/views/comfort_types/show.html.erb
<div class="row">
<div class="col-lg-1">
</div>
<div class="col-lg-2">
	<div class="panel panel-primary">
	  <div class="panel-heading">
	    <h3 class="panel-title">Name:</h3>
	  </div>
	  <div class="panel-body">
	    <%= comfort_type.name %>
	  </div>
	</div>	
</div>	
<div class="col-lg-2">
	<div class="panel panel-primary">
	  <div class="panel-heading">
	    <h3 class="panel-title">Price per day:</h3>
	  </div>
	  <div class="panel-body">
	    <%= number_to_currency(comfort_type.price, :unit => "zł") %>
	  </div>
	</div>		
</div>	
<div class="col-lg-7">
</div>		
</div>
<div class="row">
<div class="col-lg-1">
</div>
<div class="col-lg-2">
<%= link_to 'Edit', edit_comfort_type_path(comfort_type), :class => 'btn btn-primary' %>
<%= link_to 'Back', comfort_types_path, :class => 'btn btn-danger' %>
<div class="col-lg-9">
</div>		
</div>	

app/views/layouts/_alertnotice.html.erb
<% if alert %>       
<div class="row">
<div class="col-lg-12">
<div class="alert alert-dismissable alert-danger">
  <center><h4><%= alert %></h4></center>
</div>
</div>
</div>       
<% elsif notice %>
<div class="row">
<div class="col-lg-12">
<div class="alert alert-dismissable alert-success">
  <center><h4><%= notice %></h4></center>
</div>
</div>
</div>       
<% end %>

app/views/layouts/_footer.html.erb
<footer>
<div class="row">
	<div class="col-lg-12">
		<ul class="list-inline">
		<li class="pull-right"><a href="#top" class="rade">Back to top</a></li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="col-lg-4">
	</div>
	<div class="col-lg-4">
		<center>	
			<ul class="breadcrumb">
			  <li class="active"><p class="lead"> 2015 © - Rent-a-car</p></li>
			</ul>
		</center>
	</div>
	<div class="col-lg-4">
	</div>
</div>
</footer>

app/views/layouts/_navbar.html.erb
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RENT-A-CAR</a>
        </div>
        <div class="navbar-collapse collapse">
        	
     <ul class="nav navbar-nav">
            <li class="<%=is_active_page?(root_path)%>"><%= link_to "Home", root_path %></li>
	        <% if current_user.try(:admin?) %>
	        <li class="<%=is_active_page?(comfort_types_path)%>"><%= link_to "Manage Comfort types", comfort_types_path %></li>
            <% end %>
     </ul>  
     <ul class="nav navbar-nav navbar-right">
       <li><% if user_signed_in? %>
         <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
         <%else%> 
         <%= link_to "Sign in", new_user_session_path%>
         <%end%>
       </li>
     </ul>                                                             
        </div>
      </div>
    </div>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= favicon_link_tag("favicon.png")%>
<html>
<head>
  <title>Rent-a-car</title>
  <%= stylesheet_link_tag    'cerulean', media: 'all', 'data-turbolinks-track' => true %>
  <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>
  <%= javascript_include_tag 'cerulean', 'data-turbolinks-track' => true %>
  <%= yield(:page_javascript) if content_for?(:page_javascript) %>  
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container theme-showcase">
<%= render 'layouts/alertnotice' %>

<%= yield %>
<%= render 'layouts/footer' %>  
</div>
</body>
</html>

app/views/rents/create.js.erb
$('#rent').show();      
$('#rent').html('<strong>Rent is active !</strong>');